CREATE DATABASE debate;

CREATE TABLE `debate`.`comments` (`text` VARCHAR(255) NOT NULL ) ENGINE = InnoDB;

r.
CREATE USER 'ioan'@'%' IDENTIFIED VIA mysql_native_password USING '***';GRANT USAGE ON *.* TO 'ioan'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON `debate`.* TO 'ioan'@'%' WITH GRANT OPTION;

